In [1]:
import numpy as np

In [2]:
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# 與 flatten() 不同的是，ravel() 建立的是原來陣列的 view，
#所以在 ravel() 回傳物件中做的元素值變更，將會影響原陣列的元素值。
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
b[3]=100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [9]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [10]:
a.ravel(order='C')

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [11]:
a.ravel(order='F')

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

In [12]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
b.size

15

In [14]:
b.resize((3, 6), refcheck=False)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

In [20]:
a = np.arange(10).reshape(5, 2)
b = np.arange(6).reshape(3, 2)
# 使用 concatenate() 進行陣列的合併時，須留意除了指定的軸之外 (預設為 axis 0)，
# 其他軸的形狀必須完全相同，合併才不會發生錯誤。
np.concatenate((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [15]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [16]:
for i in a:
    print(i)

0
1
2
3
4


In [17]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
for row in b:
    print(row)

[0 1 2]
[3 4 5]


In [19]:
#如果要列出多維陣列所有元素的話，可以配合 flat 屬性。
for i in b.flat:
    print(i)

0
1
2
3
4
5


In [36]:
a = np.random.randint(1, 20, size=(3, 4))
a

array([[19, 19,  6, 19],
       [16,  8, 19,  7],
       [15,  4,  1, 13]])

In [37]:
#以上索引值對應的元素，其值都符合 "大於 10" 的條件。
# 傳入條件式，回傳值為符合條件的元素索引，不過這邊留意的是，
# 回傳的索引陣列要合併一起看
np.where(a>10)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 3, 0, 2, 0, 3], dtype=int64))

In [23]:
np.where(a > 10, "Y", "N")

array(['N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N'], dtype='<U1')

In [24]:
# nonzero 等同於 np.where(array != 0) 的語法，同樣的也是回傳符合非 0 條件的元素索引值。
np.random.seed(2)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [25]:
np.nonzero(a)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [26]:
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [27]:
np.random.seed(3)
a = np.random.randint(0, 20, 10)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [28]:
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [29]:
a.argsort()

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [30]:
# 與 np.sort() 不同的是，陣列物件.sort() 的語法會進行 in-place 排序，
# 也就是原本的陣列內容會跟著改變。
b = np.random.randint(0, 20, size=(5, 4))
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [31]:
np.sort(b, axis=0)

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [32]:
c = np.random.randint(0, 100000000, 1000000)
np.sort(c, kind='heapsort')

array([      64,       96,      310, ..., 99999479, 99999561, 99999830])

In [55]:
# HW
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30)).reshape((5,6),order="F")
array1

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [57]:
#2.呈上題的array，找出被6除餘1的數的索引
np.where(array1%6 == 1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))